apiVersion: v2
name: flux2-sync
type: application
version: 1.7.3
appVersion: 2.2.0
description: A Helm chart for flux2 GitRepository to sync with
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "docs: fix grammar"
