annotations:
  artifacthub.io/changes: |
    - "[Added]: Support extraEnv value setting for all flux controllers"
apiVersion: v2
appVersion: 2.0.0
description: A Helm chart for flux2
name: flux2
sources:
- https://github.com/fluxcd-community/helm-charts
type: application
version: 2.9.1
