apiVersion: v2
name: flux2-notification
type: application
version: 1.5.0
appVersion: 0.36.0
description: A Helm chart for flux2 alerts and the needed providers and secrets
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Chore]: Update App Version to upstream 0.36.0"
